---
application:
  name: "hyperlocal"
  project: "hyperlocal"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "hyperlocal"
  version: "12"
routers:
- name: "main-hyperlocal"
  routes:
  - application_name: "hyperlocal"
    paths:
    - "/*"
